services:
  qdrant:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.qdrant
    container_name: rnd_chatbot_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - rag-chatbot-network 
    volumes:
      - ./app/qdrant_data/qdrant_storage:/qdrant/storage
      - ./app/qdrant_data/qdrant_snapshots:/qdrant/snapshots
    runtime: nvidia
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
      - QDRANT__SERVICE__ENABLE_TLS=false